variables:
  KUBE_CONTEXT: echelon-it/k8s-connection:k8s-connection
  
stages:
    - build
    - deploy

build_image:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/echelon-it/k8s-data/sample:v1 .
    - docker push $CI_REGISTRY/echelon-it/k8s-data/sample:v1
    - echo "Image built"

deploy_project:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl get pods
    - kubectl get nodes -o wide
    - echo "Deployment LOGIN-APP to K8S"
    - ls $CI_PROJECT_DIR/k8s-files
    - kubectl get pods
    - kubectl get svc
